title: Performance Scaling for sMRI Surface Parcellations
email: sahahn@uvm.edu
description: > 
  This include the project documentation and is designed
  to act as supplementary material for the paper and broader research project.
source: docs/
markdown: kramdown
permalink: /:year/:title:output_ext
theme: jekyll-theme-cayman