title: Surface Parcellation Scaling
email: your-email@domain.com
description: > 
  Parcellation project documentation.
baseurl: "/docs"

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext