title: Surface Parcellation Scaling
email: your-email@domain.com
description: > 
  Parcellation project documentation.
source: docs/
# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
theme: jekyll-theme-cayman